services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: studysync
      POSTGRES_PASSWORD: studysync
      POSTGRES_DB: studysync
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U studysync -d studysync"]
      interval: 3s
      timeout: 3s
      retries: 10
    ports: ["5432:5432"]

  api:
    build: .
    env_file: .env     # <— important
    ports: ["8000:8000"]
    volumes:
      - ./app:/app/app
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pgdata:
