name: CI

on: [push, pull_request]

jobs:
  backend-sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python -m compileall app

  extension-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd extension
          zip -r ../studysync-extension.zip . -x "*.DS_Store"
      - uses: actions/upload-artifact@v4
        with:
          name: studysync-extension.zip
          path: studysync-extension.zip
